// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harvester.Outputs
{

    [OutputType]
    public sealed class VirtualMachineCloudinit
    {
        public readonly string? NetworkData;
        public readonly string? NetworkDataBase64;
        public readonly string? NetworkDataSecretName;
        public readonly string? Type;
        public readonly string? UserData;
        public readonly string? UserDataBase64;
        public readonly string? UserDataSecretName;

        [OutputConstructor]
        private VirtualMachineCloudinit(
            string? networkData,

            string? networkDataBase64,

            string? networkDataSecretName,

            string? type,

            string? userData,

            string? userDataBase64,

            string? userDataSecretName)
        {
            NetworkData = networkData;
            NetworkDataBase64 = networkDataBase64;
            NetworkDataSecretName = networkDataSecretName;
            Type = type;
            UserData = userData;
            UserDataBase64 = userDataBase64;
            UserDataSecretName = userDataSecretName;
        }
    }
}
