// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package harvester

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/huaxk/pulumi-harvester/sdk/go/harvester"
// 	"github.com/pulumi/pulumi-harvester/sdk/go/harvester"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := harvester.LookupNetwork(ctx, &GetNetworkArgs{
// 			Name:      "vlan1",
// 			Namespace: pulumi.StringRef("harvester-public"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupNetwork(ctx *pulumi.Context, args *LookupNetworkArgs, opts ...pulumi.InvokeOption) (*LookupNetworkResult, error) {
	var rv LookupNetworkResult
	err := ctx.Invoke("harvester:index/getNetwork:getNetwork", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetwork.
type LookupNetworkArgs struct {
	// A unique name
	Name      string  `pulumi:"name"`
	Namespace *string `pulumi:"namespace"`
}

// A collection of values returned by getNetwork.
type LookupNetworkResult struct {
	Config string `pulumi:"config"`
	// Any text you want that better describes this resource
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A unique name
	Name      string  `pulumi:"name"`
	Namespace *string `pulumi:"namespace"`
	// e.g. 172.16.0.1/24
	RouteCidr         string `pulumi:"routeCidr"`
	RouteConnectivity string `pulumi:"routeConnectivity"`
	RouteDhcpServerIp string `pulumi:"routeDhcpServerIp"`
	// e.g. 172.16.0.1
	RouteGateway string                 `pulumi:"routeGateway"`
	RouteMode    string                 `pulumi:"routeMode"`
	State        string                 `pulumi:"state"`
	Tags         map[string]interface{} `pulumi:"tags"`
	// e.g. 1-4094
	VlanId int `pulumi:"vlanId"`
}

func LookupNetworkOutput(ctx *pulumi.Context, args LookupNetworkOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNetworkResult, error) {
			args := v.(LookupNetworkArgs)
			r, err := LookupNetwork(ctx, &args, opts...)
			var s LookupNetworkResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNetworkResultOutput)
}

// A collection of arguments for invoking getNetwork.
type LookupNetworkOutputArgs struct {
	// A unique name
	Name      pulumi.StringInput    `pulumi:"name"`
	Namespace pulumi.StringPtrInput `pulumi:"namespace"`
}

func (LookupNetworkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkArgs)(nil)).Elem()
}

// A collection of values returned by getNetwork.
type LookupNetworkResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkResult)(nil)).Elem()
}

func (o LookupNetworkResultOutput) ToLookupNetworkResultOutput() LookupNetworkResultOutput {
	return o
}

func (o LookupNetworkResultOutput) ToLookupNetworkResultOutputWithContext(ctx context.Context) LookupNetworkResultOutput {
	return o
}

func (o LookupNetworkResultOutput) Config() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Config }).(pulumi.StringOutput)
}

// Any text you want that better describes this resource
func (o LookupNetworkResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetworkResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Id }).(pulumi.StringOutput)
}

// A unique name
func (o LookupNetworkResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkResult) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

// e.g. 172.16.0.1/24
func (o LookupNetworkResultOutput) RouteCidr() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.RouteCidr }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) RouteConnectivity() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.RouteConnectivity }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) RouteDhcpServerIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.RouteDhcpServerIp }).(pulumi.StringOutput)
}

// e.g. 172.16.0.1
func (o LookupNetworkResultOutput) RouteGateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.RouteGateway }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) RouteMode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.RouteMode }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Tags() pulumi.MapOutput {
	return o.ApplyT(func(v LookupNetworkResult) map[string]interface{} { return v.Tags }).(pulumi.MapOutput)
}

// e.g. 1-4094
func (o LookupNetworkResultOutput) VlanId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.VlanId }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkResultOutput{})
}
