// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package harvester

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Import
//
// ```sh
//  $ pulumi import harvester:index/network:Network foo <Namespace>/<Name>
// ```
type Network struct {
	pulumi.CustomResourceState

	Config pulumi.StringOutput `pulumi:"config"`
	// Any text you want that better describes this resource
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// A unique name
	Name      pulumi.StringOutput    `pulumi:"name"`
	Namespace pulumi.StringPtrOutput `pulumi:"namespace"`
	// e.g. 172.16.0.1/24
	RouteCidr         pulumi.StringPtrOutput `pulumi:"routeCidr"`
	RouteConnectivity pulumi.StringOutput    `pulumi:"routeConnectivity"`
	RouteDhcpServerIp pulumi.StringPtrOutput `pulumi:"routeDhcpServerIp"`
	// e.g. 172.16.0.1
	RouteGateway pulumi.StringPtrOutput `pulumi:"routeGateway"`
	RouteMode    pulumi.StringPtrOutput `pulumi:"routeMode"`
	State        pulumi.StringOutput    `pulumi:"state"`
	Tags         pulumi.MapOutput       `pulumi:"tags"`
	// e.g. 1-4094
	VlanId pulumi.IntOutput `pulumi:"vlanId"`
}

// NewNetwork registers a new resource with the given unique name, arguments, and options.
func NewNetwork(ctx *pulumi.Context,
	name string, args *NetworkArgs, opts ...pulumi.ResourceOption) (*Network, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.VlanId == nil {
		return nil, errors.New("invalid value for required argument 'VlanId'")
	}
	var resource Network
	err := ctx.RegisterResource("harvester:index/network:Network", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetwork gets an existing Network resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetwork(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkState, opts ...pulumi.ResourceOption) (*Network, error) {
	var resource Network
	err := ctx.ReadResource("harvester:index/network:Network", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Network resources.
type networkState struct {
	Config *string `pulumi:"config"`
	// Any text you want that better describes this resource
	Description *string `pulumi:"description"`
	// A unique name
	Name      *string `pulumi:"name"`
	Namespace *string `pulumi:"namespace"`
	// e.g. 172.16.0.1/24
	RouteCidr         *string `pulumi:"routeCidr"`
	RouteConnectivity *string `pulumi:"routeConnectivity"`
	RouteDhcpServerIp *string `pulumi:"routeDhcpServerIp"`
	// e.g. 172.16.0.1
	RouteGateway *string                `pulumi:"routeGateway"`
	RouteMode    *string                `pulumi:"routeMode"`
	State        *string                `pulumi:"state"`
	Tags         map[string]interface{} `pulumi:"tags"`
	// e.g. 1-4094
	VlanId *int `pulumi:"vlanId"`
}

type NetworkState struct {
	Config pulumi.StringPtrInput
	// Any text you want that better describes this resource
	Description pulumi.StringPtrInput
	// A unique name
	Name      pulumi.StringPtrInput
	Namespace pulumi.StringPtrInput
	// e.g. 172.16.0.1/24
	RouteCidr         pulumi.StringPtrInput
	RouteConnectivity pulumi.StringPtrInput
	RouteDhcpServerIp pulumi.StringPtrInput
	// e.g. 172.16.0.1
	RouteGateway pulumi.StringPtrInput
	RouteMode    pulumi.StringPtrInput
	State        pulumi.StringPtrInput
	Tags         pulumi.MapInput
	// e.g. 1-4094
	VlanId pulumi.IntPtrInput
}

func (NetworkState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkState)(nil)).Elem()
}

type networkArgs struct {
	Config *string `pulumi:"config"`
	// Any text you want that better describes this resource
	Description *string `pulumi:"description"`
	// A unique name
	Name      *string `pulumi:"name"`
	Namespace *string `pulumi:"namespace"`
	// e.g. 172.16.0.1/24
	RouteCidr         *string `pulumi:"routeCidr"`
	RouteDhcpServerIp *string `pulumi:"routeDhcpServerIp"`
	// e.g. 172.16.0.1
	RouteGateway *string                `pulumi:"routeGateway"`
	RouteMode    *string                `pulumi:"routeMode"`
	Tags         map[string]interface{} `pulumi:"tags"`
	// e.g. 1-4094
	VlanId int `pulumi:"vlanId"`
}

// The set of arguments for constructing a Network resource.
type NetworkArgs struct {
	Config pulumi.StringPtrInput
	// Any text you want that better describes this resource
	Description pulumi.StringPtrInput
	// A unique name
	Name      pulumi.StringPtrInput
	Namespace pulumi.StringPtrInput
	// e.g. 172.16.0.1/24
	RouteCidr         pulumi.StringPtrInput
	RouteDhcpServerIp pulumi.StringPtrInput
	// e.g. 172.16.0.1
	RouteGateway pulumi.StringPtrInput
	RouteMode    pulumi.StringPtrInput
	Tags         pulumi.MapInput
	// e.g. 1-4094
	VlanId pulumi.IntInput
}

func (NetworkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkArgs)(nil)).Elem()
}

type NetworkInput interface {
	pulumi.Input

	ToNetworkOutput() NetworkOutput
	ToNetworkOutputWithContext(ctx context.Context) NetworkOutput
}

func (*Network) ElementType() reflect.Type {
	return reflect.TypeOf((**Network)(nil)).Elem()
}

func (i *Network) ToNetworkOutput() NetworkOutput {
	return i.ToNetworkOutputWithContext(context.Background())
}

func (i *Network) ToNetworkOutputWithContext(ctx context.Context) NetworkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkOutput)
}

// NetworkArrayInput is an input type that accepts NetworkArray and NetworkArrayOutput values.
// You can construct a concrete instance of `NetworkArrayInput` via:
//
//          NetworkArray{ NetworkArgs{...} }
type NetworkArrayInput interface {
	pulumi.Input

	ToNetworkArrayOutput() NetworkArrayOutput
	ToNetworkArrayOutputWithContext(context.Context) NetworkArrayOutput
}

type NetworkArray []NetworkInput

func (NetworkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Network)(nil)).Elem()
}

func (i NetworkArray) ToNetworkArrayOutput() NetworkArrayOutput {
	return i.ToNetworkArrayOutputWithContext(context.Background())
}

func (i NetworkArray) ToNetworkArrayOutputWithContext(ctx context.Context) NetworkArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkArrayOutput)
}

// NetworkMapInput is an input type that accepts NetworkMap and NetworkMapOutput values.
// You can construct a concrete instance of `NetworkMapInput` via:
//
//          NetworkMap{ "key": NetworkArgs{...} }
type NetworkMapInput interface {
	pulumi.Input

	ToNetworkMapOutput() NetworkMapOutput
	ToNetworkMapOutputWithContext(context.Context) NetworkMapOutput
}

type NetworkMap map[string]NetworkInput

func (NetworkMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Network)(nil)).Elem()
}

func (i NetworkMap) ToNetworkMapOutput() NetworkMapOutput {
	return i.ToNetworkMapOutputWithContext(context.Background())
}

func (i NetworkMap) ToNetworkMapOutputWithContext(ctx context.Context) NetworkMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkMapOutput)
}

type NetworkOutput struct{ *pulumi.OutputState }

func (NetworkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Network)(nil)).Elem()
}

func (o NetworkOutput) ToNetworkOutput() NetworkOutput {
	return o
}

func (o NetworkOutput) ToNetworkOutputWithContext(ctx context.Context) NetworkOutput {
	return o
}

type NetworkArrayOutput struct{ *pulumi.OutputState }

func (NetworkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Network)(nil)).Elem()
}

func (o NetworkArrayOutput) ToNetworkArrayOutput() NetworkArrayOutput {
	return o
}

func (o NetworkArrayOutput) ToNetworkArrayOutputWithContext(ctx context.Context) NetworkArrayOutput {
	return o
}

func (o NetworkArrayOutput) Index(i pulumi.IntInput) NetworkOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Network {
		return vs[0].([]*Network)[vs[1].(int)]
	}).(NetworkOutput)
}

type NetworkMapOutput struct{ *pulumi.OutputState }

func (NetworkMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Network)(nil)).Elem()
}

func (o NetworkMapOutput) ToNetworkMapOutput() NetworkMapOutput {
	return o
}

func (o NetworkMapOutput) ToNetworkMapOutputWithContext(ctx context.Context) NetworkMapOutput {
	return o
}

func (o NetworkMapOutput) MapIndex(k pulumi.StringInput) NetworkOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Network {
		return vs[0].(map[string]*Network)[vs[1].(string)]
	}).(NetworkOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkInput)(nil)).Elem(), &Network{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkArrayInput)(nil)).Elem(), NetworkArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkMapInput)(nil)).Elem(), NetworkMap{})
	pulumi.RegisterOutputType(NetworkOutput{})
	pulumi.RegisterOutputType(NetworkArrayOutput{})
	pulumi.RegisterOutputType(NetworkMapOutput{})
}
