// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package harvester

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type VirtualMachineCloudinit struct {
	NetworkData           *string `pulumi:"networkData"`
	NetworkDataBase64     *string `pulumi:"networkDataBase64"`
	NetworkDataSecretName *string `pulumi:"networkDataSecretName"`
	Type                  *string `pulumi:"type"`
	UserData              *string `pulumi:"userData"`
	UserDataBase64        *string `pulumi:"userDataBase64"`
	UserDataSecretName    *string `pulumi:"userDataSecretName"`
}

// VirtualMachineCloudinitInput is an input type that accepts VirtualMachineCloudinitArgs and VirtualMachineCloudinitOutput values.
// You can construct a concrete instance of `VirtualMachineCloudinitInput` via:
//
//          VirtualMachineCloudinitArgs{...}
type VirtualMachineCloudinitInput interface {
	pulumi.Input

	ToVirtualMachineCloudinitOutput() VirtualMachineCloudinitOutput
	ToVirtualMachineCloudinitOutputWithContext(context.Context) VirtualMachineCloudinitOutput
}

type VirtualMachineCloudinitArgs struct {
	NetworkData           pulumi.StringPtrInput `pulumi:"networkData"`
	NetworkDataBase64     pulumi.StringPtrInput `pulumi:"networkDataBase64"`
	NetworkDataSecretName pulumi.StringPtrInput `pulumi:"networkDataSecretName"`
	Type                  pulumi.StringPtrInput `pulumi:"type"`
	UserData              pulumi.StringPtrInput `pulumi:"userData"`
	UserDataBase64        pulumi.StringPtrInput `pulumi:"userDataBase64"`
	UserDataSecretName    pulumi.StringPtrInput `pulumi:"userDataSecretName"`
}

func (VirtualMachineCloudinitArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineCloudinit)(nil)).Elem()
}

func (i VirtualMachineCloudinitArgs) ToVirtualMachineCloudinitOutput() VirtualMachineCloudinitOutput {
	return i.ToVirtualMachineCloudinitOutputWithContext(context.Background())
}

func (i VirtualMachineCloudinitArgs) ToVirtualMachineCloudinitOutputWithContext(ctx context.Context) VirtualMachineCloudinitOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineCloudinitOutput)
}

func (i VirtualMachineCloudinitArgs) ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput {
	return i.ToVirtualMachineCloudinitPtrOutputWithContext(context.Background())
}

func (i VirtualMachineCloudinitArgs) ToVirtualMachineCloudinitPtrOutputWithContext(ctx context.Context) VirtualMachineCloudinitPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineCloudinitOutput).ToVirtualMachineCloudinitPtrOutputWithContext(ctx)
}

// VirtualMachineCloudinitPtrInput is an input type that accepts VirtualMachineCloudinitArgs, VirtualMachineCloudinitPtr and VirtualMachineCloudinitPtrOutput values.
// You can construct a concrete instance of `VirtualMachineCloudinitPtrInput` via:
//
//          VirtualMachineCloudinitArgs{...}
//
//  or:
//
//          nil
type VirtualMachineCloudinitPtrInput interface {
	pulumi.Input

	ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput
	ToVirtualMachineCloudinitPtrOutputWithContext(context.Context) VirtualMachineCloudinitPtrOutput
}

type virtualMachineCloudinitPtrType VirtualMachineCloudinitArgs

func VirtualMachineCloudinitPtr(v *VirtualMachineCloudinitArgs) VirtualMachineCloudinitPtrInput {
	return (*virtualMachineCloudinitPtrType)(v)
}

func (*virtualMachineCloudinitPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualMachineCloudinit)(nil)).Elem()
}

func (i *virtualMachineCloudinitPtrType) ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput {
	return i.ToVirtualMachineCloudinitPtrOutputWithContext(context.Background())
}

func (i *virtualMachineCloudinitPtrType) ToVirtualMachineCloudinitPtrOutputWithContext(ctx context.Context) VirtualMachineCloudinitPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineCloudinitPtrOutput)
}

type VirtualMachineCloudinitOutput struct{ *pulumi.OutputState }

func (VirtualMachineCloudinitOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineCloudinit)(nil)).Elem()
}

func (o VirtualMachineCloudinitOutput) ToVirtualMachineCloudinitOutput() VirtualMachineCloudinitOutput {
	return o
}

func (o VirtualMachineCloudinitOutput) ToVirtualMachineCloudinitOutputWithContext(ctx context.Context) VirtualMachineCloudinitOutput {
	return o
}

func (o VirtualMachineCloudinitOutput) ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput {
	return o.ToVirtualMachineCloudinitPtrOutputWithContext(context.Background())
}

func (o VirtualMachineCloudinitOutput) ToVirtualMachineCloudinitPtrOutputWithContext(ctx context.Context) VirtualMachineCloudinitPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v VirtualMachineCloudinit) *VirtualMachineCloudinit {
		return &v
	}).(VirtualMachineCloudinitPtrOutput)
}

func (o VirtualMachineCloudinitOutput) NetworkData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.NetworkData }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) NetworkDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.NetworkDataBase64 }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) NetworkDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.NetworkDataSecretName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) UserData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.UserData }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) UserDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.UserDataBase64 }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) UserDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.UserDataSecretName }).(pulumi.StringPtrOutput)
}

type VirtualMachineCloudinitPtrOutput struct{ *pulumi.OutputState }

func (VirtualMachineCloudinitPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualMachineCloudinit)(nil)).Elem()
}

func (o VirtualMachineCloudinitPtrOutput) ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput {
	return o
}

func (o VirtualMachineCloudinitPtrOutput) ToVirtualMachineCloudinitPtrOutputWithContext(ctx context.Context) VirtualMachineCloudinitPtrOutput {
	return o
}

func (o VirtualMachineCloudinitPtrOutput) Elem() VirtualMachineCloudinitOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) VirtualMachineCloudinit {
		if v != nil {
			return *v
		}
		var ret VirtualMachineCloudinit
		return ret
	}).(VirtualMachineCloudinitOutput)
}

func (o VirtualMachineCloudinitPtrOutput) NetworkData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.NetworkData
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) NetworkDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.NetworkDataBase64
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) NetworkDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.NetworkDataSecretName
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.Type
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) UserData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.UserData
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) UserDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.UserDataBase64
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) UserDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.UserDataSecretName
	}).(pulumi.StringPtrOutput)
}

type VirtualMachineDisk struct {
	AccessMode         *string `pulumi:"accessMode"`
	AutoDelete         *bool   `pulumi:"autoDelete"`
	BootOrder          *int    `pulumi:"bootOrder"`
	Bus                *string `pulumi:"bus"`
	ContainerImageName *string `pulumi:"containerImageName"`
	ExistingVolumeName *string `pulumi:"existingVolumeName"`
	HotPlug            *bool   `pulumi:"hotPlug"`
	Image              *string `pulumi:"image"`
	// A unique name
	Name             string  `pulumi:"name"`
	Size             *string `pulumi:"size"`
	StorageClassName *string `pulumi:"storageClassName"`
	Type             *string `pulumi:"type"`
	VolumeMode       *string `pulumi:"volumeMode"`
	VolumeName       *string `pulumi:"volumeName"`
}

// VirtualMachineDiskInput is an input type that accepts VirtualMachineDiskArgs and VirtualMachineDiskOutput values.
// You can construct a concrete instance of `VirtualMachineDiskInput` via:
//
//          VirtualMachineDiskArgs{...}
type VirtualMachineDiskInput interface {
	pulumi.Input

	ToVirtualMachineDiskOutput() VirtualMachineDiskOutput
	ToVirtualMachineDiskOutputWithContext(context.Context) VirtualMachineDiskOutput
}

type VirtualMachineDiskArgs struct {
	AccessMode         pulumi.StringPtrInput `pulumi:"accessMode"`
	AutoDelete         pulumi.BoolPtrInput   `pulumi:"autoDelete"`
	BootOrder          pulumi.IntPtrInput    `pulumi:"bootOrder"`
	Bus                pulumi.StringPtrInput `pulumi:"bus"`
	ContainerImageName pulumi.StringPtrInput `pulumi:"containerImageName"`
	ExistingVolumeName pulumi.StringPtrInput `pulumi:"existingVolumeName"`
	HotPlug            pulumi.BoolPtrInput   `pulumi:"hotPlug"`
	Image              pulumi.StringPtrInput `pulumi:"image"`
	// A unique name
	Name             pulumi.StringInput    `pulumi:"name"`
	Size             pulumi.StringPtrInput `pulumi:"size"`
	StorageClassName pulumi.StringPtrInput `pulumi:"storageClassName"`
	Type             pulumi.StringPtrInput `pulumi:"type"`
	VolumeMode       pulumi.StringPtrInput `pulumi:"volumeMode"`
	VolumeName       pulumi.StringPtrInput `pulumi:"volumeName"`
}

func (VirtualMachineDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineDisk)(nil)).Elem()
}

func (i VirtualMachineDiskArgs) ToVirtualMachineDiskOutput() VirtualMachineDiskOutput {
	return i.ToVirtualMachineDiskOutputWithContext(context.Background())
}

func (i VirtualMachineDiskArgs) ToVirtualMachineDiskOutputWithContext(ctx context.Context) VirtualMachineDiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineDiskOutput)
}

// VirtualMachineDiskArrayInput is an input type that accepts VirtualMachineDiskArray and VirtualMachineDiskArrayOutput values.
// You can construct a concrete instance of `VirtualMachineDiskArrayInput` via:
//
//          VirtualMachineDiskArray{ VirtualMachineDiskArgs{...} }
type VirtualMachineDiskArrayInput interface {
	pulumi.Input

	ToVirtualMachineDiskArrayOutput() VirtualMachineDiskArrayOutput
	ToVirtualMachineDiskArrayOutputWithContext(context.Context) VirtualMachineDiskArrayOutput
}

type VirtualMachineDiskArray []VirtualMachineDiskInput

func (VirtualMachineDiskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualMachineDisk)(nil)).Elem()
}

func (i VirtualMachineDiskArray) ToVirtualMachineDiskArrayOutput() VirtualMachineDiskArrayOutput {
	return i.ToVirtualMachineDiskArrayOutputWithContext(context.Background())
}

func (i VirtualMachineDiskArray) ToVirtualMachineDiskArrayOutputWithContext(ctx context.Context) VirtualMachineDiskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineDiskArrayOutput)
}

type VirtualMachineDiskOutput struct{ *pulumi.OutputState }

func (VirtualMachineDiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineDisk)(nil)).Elem()
}

func (o VirtualMachineDiskOutput) ToVirtualMachineDiskOutput() VirtualMachineDiskOutput {
	return o
}

func (o VirtualMachineDiskOutput) ToVirtualMachineDiskOutputWithContext(ctx context.Context) VirtualMachineDiskOutput {
	return o
}

func (o VirtualMachineDiskOutput) AccessMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.AccessMode }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) AutoDelete() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *bool { return v.AutoDelete }).(pulumi.BoolPtrOutput)
}

func (o VirtualMachineDiskOutput) BootOrder() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *int { return v.BootOrder }).(pulumi.IntPtrOutput)
}

func (o VirtualMachineDiskOutput) Bus() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.Bus }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) ContainerImageName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.ContainerImageName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) ExistingVolumeName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.ExistingVolumeName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) HotPlug() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *bool { return v.HotPlug }).(pulumi.BoolPtrOutput)
}

func (o VirtualMachineDiskOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.Image }).(pulumi.StringPtrOutput)
}

// A unique name
func (o VirtualMachineDiskOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v VirtualMachineDisk) string { return v.Name }).(pulumi.StringOutput)
}

func (o VirtualMachineDiskOutput) Size() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.Size }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) StorageClassName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.StorageClassName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) VolumeMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.VolumeMode }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) VolumeName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.VolumeName }).(pulumi.StringPtrOutput)
}

type VirtualMachineDiskArrayOutput struct{ *pulumi.OutputState }

func (VirtualMachineDiskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualMachineDisk)(nil)).Elem()
}

func (o VirtualMachineDiskArrayOutput) ToVirtualMachineDiskArrayOutput() VirtualMachineDiskArrayOutput {
	return o
}

func (o VirtualMachineDiskArrayOutput) ToVirtualMachineDiskArrayOutputWithContext(ctx context.Context) VirtualMachineDiskArrayOutput {
	return o
}

func (o VirtualMachineDiskArrayOutput) Index(i pulumi.IntInput) VirtualMachineDiskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) VirtualMachineDisk {
		return vs[0].([]VirtualMachineDisk)[vs[1].(int)]
	}).(VirtualMachineDiskOutput)
}

type VirtualMachineNetworkInterface struct {
	InterfaceName *string `pulumi:"interfaceName"`
	IpAddress     *string `pulumi:"ipAddress"`
	MacAddress    *string `pulumi:"macAddress"`
	Model         *string `pulumi:"model"`
	// A unique name
	Name        string  `pulumi:"name"`
	NetworkName *string `pulumi:"networkName"`
	Type        *string `pulumi:"type"`
}

// VirtualMachineNetworkInterfaceInput is an input type that accepts VirtualMachineNetworkInterfaceArgs and VirtualMachineNetworkInterfaceOutput values.
// You can construct a concrete instance of `VirtualMachineNetworkInterfaceInput` via:
//
//          VirtualMachineNetworkInterfaceArgs{...}
type VirtualMachineNetworkInterfaceInput interface {
	pulumi.Input

	ToVirtualMachineNetworkInterfaceOutput() VirtualMachineNetworkInterfaceOutput
	ToVirtualMachineNetworkInterfaceOutputWithContext(context.Context) VirtualMachineNetworkInterfaceOutput
}

type VirtualMachineNetworkInterfaceArgs struct {
	InterfaceName pulumi.StringPtrInput `pulumi:"interfaceName"`
	IpAddress     pulumi.StringPtrInput `pulumi:"ipAddress"`
	MacAddress    pulumi.StringPtrInput `pulumi:"macAddress"`
	Model         pulumi.StringPtrInput `pulumi:"model"`
	// A unique name
	Name        pulumi.StringInput    `pulumi:"name"`
	NetworkName pulumi.StringPtrInput `pulumi:"networkName"`
	Type        pulumi.StringPtrInput `pulumi:"type"`
}

func (VirtualMachineNetworkInterfaceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineNetworkInterface)(nil)).Elem()
}

func (i VirtualMachineNetworkInterfaceArgs) ToVirtualMachineNetworkInterfaceOutput() VirtualMachineNetworkInterfaceOutput {
	return i.ToVirtualMachineNetworkInterfaceOutputWithContext(context.Background())
}

func (i VirtualMachineNetworkInterfaceArgs) ToVirtualMachineNetworkInterfaceOutputWithContext(ctx context.Context) VirtualMachineNetworkInterfaceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineNetworkInterfaceOutput)
}

// VirtualMachineNetworkInterfaceArrayInput is an input type that accepts VirtualMachineNetworkInterfaceArray and VirtualMachineNetworkInterfaceArrayOutput values.
// You can construct a concrete instance of `VirtualMachineNetworkInterfaceArrayInput` via:
//
//          VirtualMachineNetworkInterfaceArray{ VirtualMachineNetworkInterfaceArgs{...} }
type VirtualMachineNetworkInterfaceArrayInput interface {
	pulumi.Input

	ToVirtualMachineNetworkInterfaceArrayOutput() VirtualMachineNetworkInterfaceArrayOutput
	ToVirtualMachineNetworkInterfaceArrayOutputWithContext(context.Context) VirtualMachineNetworkInterfaceArrayOutput
}

type VirtualMachineNetworkInterfaceArray []VirtualMachineNetworkInterfaceInput

func (VirtualMachineNetworkInterfaceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualMachineNetworkInterface)(nil)).Elem()
}

func (i VirtualMachineNetworkInterfaceArray) ToVirtualMachineNetworkInterfaceArrayOutput() VirtualMachineNetworkInterfaceArrayOutput {
	return i.ToVirtualMachineNetworkInterfaceArrayOutputWithContext(context.Background())
}

func (i VirtualMachineNetworkInterfaceArray) ToVirtualMachineNetworkInterfaceArrayOutputWithContext(ctx context.Context) VirtualMachineNetworkInterfaceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineNetworkInterfaceArrayOutput)
}

type VirtualMachineNetworkInterfaceOutput struct{ *pulumi.OutputState }

func (VirtualMachineNetworkInterfaceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineNetworkInterface)(nil)).Elem()
}

func (o VirtualMachineNetworkInterfaceOutput) ToVirtualMachineNetworkInterfaceOutput() VirtualMachineNetworkInterfaceOutput {
	return o
}

func (o VirtualMachineNetworkInterfaceOutput) ToVirtualMachineNetworkInterfaceOutputWithContext(ctx context.Context) VirtualMachineNetworkInterfaceOutput {
	return o
}

func (o VirtualMachineNetworkInterfaceOutput) InterfaceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.InterfaceName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) IpAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.IpAddress }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) MacAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.MacAddress }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) Model() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.Model }).(pulumi.StringPtrOutput)
}

// A unique name
func (o VirtualMachineNetworkInterfaceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) string { return v.Name }).(pulumi.StringOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) NetworkName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.NetworkName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type VirtualMachineNetworkInterfaceArrayOutput struct{ *pulumi.OutputState }

func (VirtualMachineNetworkInterfaceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualMachineNetworkInterface)(nil)).Elem()
}

func (o VirtualMachineNetworkInterfaceArrayOutput) ToVirtualMachineNetworkInterfaceArrayOutput() VirtualMachineNetworkInterfaceArrayOutput {
	return o
}

func (o VirtualMachineNetworkInterfaceArrayOutput) ToVirtualMachineNetworkInterfaceArrayOutputWithContext(ctx context.Context) VirtualMachineNetworkInterfaceArrayOutput {
	return o
}

func (o VirtualMachineNetworkInterfaceArrayOutput) Index(i pulumi.IntInput) VirtualMachineNetworkInterfaceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) VirtualMachineNetworkInterface {
		return vs[0].([]VirtualMachineNetworkInterface)[vs[1].(int)]
	}).(VirtualMachineNetworkInterfaceOutput)
}

type GetVirtualMachineCloudinit struct {
	NetworkData           *string `pulumi:"networkData"`
	NetworkDataBase64     *string `pulumi:"networkDataBase64"`
	NetworkDataSecretName *string `pulumi:"networkDataSecretName"`
	Type                  *string `pulumi:"type"`
	UserData              *string `pulumi:"userData"`
	UserDataBase64        *string `pulumi:"userDataBase64"`
	UserDataSecretName    *string `pulumi:"userDataSecretName"`
}

// GetVirtualMachineCloudinitInput is an input type that accepts GetVirtualMachineCloudinitArgs and GetVirtualMachineCloudinitOutput values.
// You can construct a concrete instance of `GetVirtualMachineCloudinitInput` via:
//
//          GetVirtualMachineCloudinitArgs{...}
type GetVirtualMachineCloudinitInput interface {
	pulumi.Input

	ToGetVirtualMachineCloudinitOutput() GetVirtualMachineCloudinitOutput
	ToGetVirtualMachineCloudinitOutputWithContext(context.Context) GetVirtualMachineCloudinitOutput
}

type GetVirtualMachineCloudinitArgs struct {
	NetworkData           pulumi.StringPtrInput `pulumi:"networkData"`
	NetworkDataBase64     pulumi.StringPtrInput `pulumi:"networkDataBase64"`
	NetworkDataSecretName pulumi.StringPtrInput `pulumi:"networkDataSecretName"`
	Type                  pulumi.StringPtrInput `pulumi:"type"`
	UserData              pulumi.StringPtrInput `pulumi:"userData"`
	UserDataBase64        pulumi.StringPtrInput `pulumi:"userDataBase64"`
	UserDataSecretName    pulumi.StringPtrInput `pulumi:"userDataSecretName"`
}

func (GetVirtualMachineCloudinitArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualMachineCloudinit)(nil)).Elem()
}

func (i GetVirtualMachineCloudinitArgs) ToGetVirtualMachineCloudinitOutput() GetVirtualMachineCloudinitOutput {
	return i.ToGetVirtualMachineCloudinitOutputWithContext(context.Background())
}

func (i GetVirtualMachineCloudinitArgs) ToGetVirtualMachineCloudinitOutputWithContext(ctx context.Context) GetVirtualMachineCloudinitOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVirtualMachineCloudinitOutput)
}

// GetVirtualMachineCloudinitArrayInput is an input type that accepts GetVirtualMachineCloudinitArray and GetVirtualMachineCloudinitArrayOutput values.
// You can construct a concrete instance of `GetVirtualMachineCloudinitArrayInput` via:
//
//          GetVirtualMachineCloudinitArray{ GetVirtualMachineCloudinitArgs{...} }
type GetVirtualMachineCloudinitArrayInput interface {
	pulumi.Input

	ToGetVirtualMachineCloudinitArrayOutput() GetVirtualMachineCloudinitArrayOutput
	ToGetVirtualMachineCloudinitArrayOutputWithContext(context.Context) GetVirtualMachineCloudinitArrayOutput
}

type GetVirtualMachineCloudinitArray []GetVirtualMachineCloudinitInput

func (GetVirtualMachineCloudinitArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVirtualMachineCloudinit)(nil)).Elem()
}

func (i GetVirtualMachineCloudinitArray) ToGetVirtualMachineCloudinitArrayOutput() GetVirtualMachineCloudinitArrayOutput {
	return i.ToGetVirtualMachineCloudinitArrayOutputWithContext(context.Background())
}

func (i GetVirtualMachineCloudinitArray) ToGetVirtualMachineCloudinitArrayOutputWithContext(ctx context.Context) GetVirtualMachineCloudinitArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVirtualMachineCloudinitArrayOutput)
}

type GetVirtualMachineCloudinitOutput struct{ *pulumi.OutputState }

func (GetVirtualMachineCloudinitOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualMachineCloudinit)(nil)).Elem()
}

func (o GetVirtualMachineCloudinitOutput) ToGetVirtualMachineCloudinitOutput() GetVirtualMachineCloudinitOutput {
	return o
}

func (o GetVirtualMachineCloudinitOutput) ToGetVirtualMachineCloudinitOutputWithContext(ctx context.Context) GetVirtualMachineCloudinitOutput {
	return o
}

func (o GetVirtualMachineCloudinitOutput) NetworkData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineCloudinit) *string { return v.NetworkData }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineCloudinitOutput) NetworkDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineCloudinit) *string { return v.NetworkDataBase64 }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineCloudinitOutput) NetworkDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineCloudinit) *string { return v.NetworkDataSecretName }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineCloudinitOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineCloudinit) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineCloudinitOutput) UserData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineCloudinit) *string { return v.UserData }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineCloudinitOutput) UserDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineCloudinit) *string { return v.UserDataBase64 }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineCloudinitOutput) UserDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineCloudinit) *string { return v.UserDataSecretName }).(pulumi.StringPtrOutput)
}

type GetVirtualMachineCloudinitArrayOutput struct{ *pulumi.OutputState }

func (GetVirtualMachineCloudinitArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVirtualMachineCloudinit)(nil)).Elem()
}

func (o GetVirtualMachineCloudinitArrayOutput) ToGetVirtualMachineCloudinitArrayOutput() GetVirtualMachineCloudinitArrayOutput {
	return o
}

func (o GetVirtualMachineCloudinitArrayOutput) ToGetVirtualMachineCloudinitArrayOutputWithContext(ctx context.Context) GetVirtualMachineCloudinitArrayOutput {
	return o
}

func (o GetVirtualMachineCloudinitArrayOutput) Index(i pulumi.IntInput) GetVirtualMachineCloudinitOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetVirtualMachineCloudinit {
		return vs[0].([]GetVirtualMachineCloudinit)[vs[1].(int)]
	}).(GetVirtualMachineCloudinitOutput)
}

type GetVirtualMachineDisk struct {
	AccessMode         string  `pulumi:"accessMode"`
	AutoDelete         bool    `pulumi:"autoDelete"`
	BootOrder          *int    `pulumi:"bootOrder"`
	Bus                string  `pulumi:"bus"`
	ContainerImageName *string `pulumi:"containerImageName"`
	ExistingVolumeName *string `pulumi:"existingVolumeName"`
	HotPlug            bool    `pulumi:"hotPlug"`
	Image              *string `pulumi:"image"`
	// A unique name
	Name             string  `pulumi:"name"`
	Size             *string `pulumi:"size"`
	StorageClassName string  `pulumi:"storageClassName"`
	Type             *string `pulumi:"type"`
	VolumeMode       string  `pulumi:"volumeMode"`
	VolumeName       string  `pulumi:"volumeName"`
}

// GetVirtualMachineDiskInput is an input type that accepts GetVirtualMachineDiskArgs and GetVirtualMachineDiskOutput values.
// You can construct a concrete instance of `GetVirtualMachineDiskInput` via:
//
//          GetVirtualMachineDiskArgs{...}
type GetVirtualMachineDiskInput interface {
	pulumi.Input

	ToGetVirtualMachineDiskOutput() GetVirtualMachineDiskOutput
	ToGetVirtualMachineDiskOutputWithContext(context.Context) GetVirtualMachineDiskOutput
}

type GetVirtualMachineDiskArgs struct {
	AccessMode         pulumi.StringInput    `pulumi:"accessMode"`
	AutoDelete         pulumi.BoolInput      `pulumi:"autoDelete"`
	BootOrder          pulumi.IntPtrInput    `pulumi:"bootOrder"`
	Bus                pulumi.StringInput    `pulumi:"bus"`
	ContainerImageName pulumi.StringPtrInput `pulumi:"containerImageName"`
	ExistingVolumeName pulumi.StringPtrInput `pulumi:"existingVolumeName"`
	HotPlug            pulumi.BoolInput      `pulumi:"hotPlug"`
	Image              pulumi.StringPtrInput `pulumi:"image"`
	// A unique name
	Name             pulumi.StringInput    `pulumi:"name"`
	Size             pulumi.StringPtrInput `pulumi:"size"`
	StorageClassName pulumi.StringInput    `pulumi:"storageClassName"`
	Type             pulumi.StringPtrInput `pulumi:"type"`
	VolumeMode       pulumi.StringInput    `pulumi:"volumeMode"`
	VolumeName       pulumi.StringInput    `pulumi:"volumeName"`
}

func (GetVirtualMachineDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualMachineDisk)(nil)).Elem()
}

func (i GetVirtualMachineDiskArgs) ToGetVirtualMachineDiskOutput() GetVirtualMachineDiskOutput {
	return i.ToGetVirtualMachineDiskOutputWithContext(context.Background())
}

func (i GetVirtualMachineDiskArgs) ToGetVirtualMachineDiskOutputWithContext(ctx context.Context) GetVirtualMachineDiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVirtualMachineDiskOutput)
}

// GetVirtualMachineDiskArrayInput is an input type that accepts GetVirtualMachineDiskArray and GetVirtualMachineDiskArrayOutput values.
// You can construct a concrete instance of `GetVirtualMachineDiskArrayInput` via:
//
//          GetVirtualMachineDiskArray{ GetVirtualMachineDiskArgs{...} }
type GetVirtualMachineDiskArrayInput interface {
	pulumi.Input

	ToGetVirtualMachineDiskArrayOutput() GetVirtualMachineDiskArrayOutput
	ToGetVirtualMachineDiskArrayOutputWithContext(context.Context) GetVirtualMachineDiskArrayOutput
}

type GetVirtualMachineDiskArray []GetVirtualMachineDiskInput

func (GetVirtualMachineDiskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVirtualMachineDisk)(nil)).Elem()
}

func (i GetVirtualMachineDiskArray) ToGetVirtualMachineDiskArrayOutput() GetVirtualMachineDiskArrayOutput {
	return i.ToGetVirtualMachineDiskArrayOutputWithContext(context.Background())
}

func (i GetVirtualMachineDiskArray) ToGetVirtualMachineDiskArrayOutputWithContext(ctx context.Context) GetVirtualMachineDiskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVirtualMachineDiskArrayOutput)
}

type GetVirtualMachineDiskOutput struct{ *pulumi.OutputState }

func (GetVirtualMachineDiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualMachineDisk)(nil)).Elem()
}

func (o GetVirtualMachineDiskOutput) ToGetVirtualMachineDiskOutput() GetVirtualMachineDiskOutput {
	return o
}

func (o GetVirtualMachineDiskOutput) ToGetVirtualMachineDiskOutputWithContext(ctx context.Context) GetVirtualMachineDiskOutput {
	return o
}

func (o GetVirtualMachineDiskOutput) AccessMode() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) string { return v.AccessMode }).(pulumi.StringOutput)
}

func (o GetVirtualMachineDiskOutput) AutoDelete() pulumi.BoolOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) bool { return v.AutoDelete }).(pulumi.BoolOutput)
}

func (o GetVirtualMachineDiskOutput) BootOrder() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) *int { return v.BootOrder }).(pulumi.IntPtrOutput)
}

func (o GetVirtualMachineDiskOutput) Bus() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) string { return v.Bus }).(pulumi.StringOutput)
}

func (o GetVirtualMachineDiskOutput) ContainerImageName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) *string { return v.ContainerImageName }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineDiskOutput) ExistingVolumeName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) *string { return v.ExistingVolumeName }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineDiskOutput) HotPlug() pulumi.BoolOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) bool { return v.HotPlug }).(pulumi.BoolOutput)
}

func (o GetVirtualMachineDiskOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) *string { return v.Image }).(pulumi.StringPtrOutput)
}

// A unique name
func (o GetVirtualMachineDiskOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetVirtualMachineDiskOutput) Size() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) *string { return v.Size }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineDiskOutput) StorageClassName() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) string { return v.StorageClassName }).(pulumi.StringOutput)
}

func (o GetVirtualMachineDiskOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineDiskOutput) VolumeMode() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) string { return v.VolumeMode }).(pulumi.StringOutput)
}

func (o GetVirtualMachineDiskOutput) VolumeName() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineDisk) string { return v.VolumeName }).(pulumi.StringOutput)
}

type GetVirtualMachineDiskArrayOutput struct{ *pulumi.OutputState }

func (GetVirtualMachineDiskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVirtualMachineDisk)(nil)).Elem()
}

func (o GetVirtualMachineDiskArrayOutput) ToGetVirtualMachineDiskArrayOutput() GetVirtualMachineDiskArrayOutput {
	return o
}

func (o GetVirtualMachineDiskArrayOutput) ToGetVirtualMachineDiskArrayOutputWithContext(ctx context.Context) GetVirtualMachineDiskArrayOutput {
	return o
}

func (o GetVirtualMachineDiskArrayOutput) Index(i pulumi.IntInput) GetVirtualMachineDiskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetVirtualMachineDisk {
		return vs[0].([]GetVirtualMachineDisk)[vs[1].(int)]
	}).(GetVirtualMachineDiskOutput)
}

type GetVirtualMachineNetworkInterface struct {
	InterfaceName string  `pulumi:"interfaceName"`
	IpAddress     string  `pulumi:"ipAddress"`
	MacAddress    string  `pulumi:"macAddress"`
	Model         *string `pulumi:"model"`
	// A unique name
	Name        string  `pulumi:"name"`
	NetworkName *string `pulumi:"networkName"`
	Type        string  `pulumi:"type"`
}

// GetVirtualMachineNetworkInterfaceInput is an input type that accepts GetVirtualMachineNetworkInterfaceArgs and GetVirtualMachineNetworkInterfaceOutput values.
// You can construct a concrete instance of `GetVirtualMachineNetworkInterfaceInput` via:
//
//          GetVirtualMachineNetworkInterfaceArgs{...}
type GetVirtualMachineNetworkInterfaceInput interface {
	pulumi.Input

	ToGetVirtualMachineNetworkInterfaceOutput() GetVirtualMachineNetworkInterfaceOutput
	ToGetVirtualMachineNetworkInterfaceOutputWithContext(context.Context) GetVirtualMachineNetworkInterfaceOutput
}

type GetVirtualMachineNetworkInterfaceArgs struct {
	InterfaceName pulumi.StringInput    `pulumi:"interfaceName"`
	IpAddress     pulumi.StringInput    `pulumi:"ipAddress"`
	MacAddress    pulumi.StringInput    `pulumi:"macAddress"`
	Model         pulumi.StringPtrInput `pulumi:"model"`
	// A unique name
	Name        pulumi.StringInput    `pulumi:"name"`
	NetworkName pulumi.StringPtrInput `pulumi:"networkName"`
	Type        pulumi.StringInput    `pulumi:"type"`
}

func (GetVirtualMachineNetworkInterfaceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualMachineNetworkInterface)(nil)).Elem()
}

func (i GetVirtualMachineNetworkInterfaceArgs) ToGetVirtualMachineNetworkInterfaceOutput() GetVirtualMachineNetworkInterfaceOutput {
	return i.ToGetVirtualMachineNetworkInterfaceOutputWithContext(context.Background())
}

func (i GetVirtualMachineNetworkInterfaceArgs) ToGetVirtualMachineNetworkInterfaceOutputWithContext(ctx context.Context) GetVirtualMachineNetworkInterfaceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVirtualMachineNetworkInterfaceOutput)
}

// GetVirtualMachineNetworkInterfaceArrayInput is an input type that accepts GetVirtualMachineNetworkInterfaceArray and GetVirtualMachineNetworkInterfaceArrayOutput values.
// You can construct a concrete instance of `GetVirtualMachineNetworkInterfaceArrayInput` via:
//
//          GetVirtualMachineNetworkInterfaceArray{ GetVirtualMachineNetworkInterfaceArgs{...} }
type GetVirtualMachineNetworkInterfaceArrayInput interface {
	pulumi.Input

	ToGetVirtualMachineNetworkInterfaceArrayOutput() GetVirtualMachineNetworkInterfaceArrayOutput
	ToGetVirtualMachineNetworkInterfaceArrayOutputWithContext(context.Context) GetVirtualMachineNetworkInterfaceArrayOutput
}

type GetVirtualMachineNetworkInterfaceArray []GetVirtualMachineNetworkInterfaceInput

func (GetVirtualMachineNetworkInterfaceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVirtualMachineNetworkInterface)(nil)).Elem()
}

func (i GetVirtualMachineNetworkInterfaceArray) ToGetVirtualMachineNetworkInterfaceArrayOutput() GetVirtualMachineNetworkInterfaceArrayOutput {
	return i.ToGetVirtualMachineNetworkInterfaceArrayOutputWithContext(context.Background())
}

func (i GetVirtualMachineNetworkInterfaceArray) ToGetVirtualMachineNetworkInterfaceArrayOutputWithContext(ctx context.Context) GetVirtualMachineNetworkInterfaceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVirtualMachineNetworkInterfaceArrayOutput)
}

type GetVirtualMachineNetworkInterfaceOutput struct{ *pulumi.OutputState }

func (GetVirtualMachineNetworkInterfaceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualMachineNetworkInterface)(nil)).Elem()
}

func (o GetVirtualMachineNetworkInterfaceOutput) ToGetVirtualMachineNetworkInterfaceOutput() GetVirtualMachineNetworkInterfaceOutput {
	return o
}

func (o GetVirtualMachineNetworkInterfaceOutput) ToGetVirtualMachineNetworkInterfaceOutputWithContext(ctx context.Context) GetVirtualMachineNetworkInterfaceOutput {
	return o
}

func (o GetVirtualMachineNetworkInterfaceOutput) InterfaceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineNetworkInterface) string { return v.InterfaceName }).(pulumi.StringOutput)
}

func (o GetVirtualMachineNetworkInterfaceOutput) IpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineNetworkInterface) string { return v.IpAddress }).(pulumi.StringOutput)
}

func (o GetVirtualMachineNetworkInterfaceOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineNetworkInterface) string { return v.MacAddress }).(pulumi.StringOutput)
}

func (o GetVirtualMachineNetworkInterfaceOutput) Model() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineNetworkInterface) *string { return v.Model }).(pulumi.StringPtrOutput)
}

// A unique name
func (o GetVirtualMachineNetworkInterfaceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineNetworkInterface) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetVirtualMachineNetworkInterfaceOutput) NetworkName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetVirtualMachineNetworkInterface) *string { return v.NetworkName }).(pulumi.StringPtrOutput)
}

func (o GetVirtualMachineNetworkInterfaceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualMachineNetworkInterface) string { return v.Type }).(pulumi.StringOutput)
}

type GetVirtualMachineNetworkInterfaceArrayOutput struct{ *pulumi.OutputState }

func (GetVirtualMachineNetworkInterfaceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVirtualMachineNetworkInterface)(nil)).Elem()
}

func (o GetVirtualMachineNetworkInterfaceArrayOutput) ToGetVirtualMachineNetworkInterfaceArrayOutput() GetVirtualMachineNetworkInterfaceArrayOutput {
	return o
}

func (o GetVirtualMachineNetworkInterfaceArrayOutput) ToGetVirtualMachineNetworkInterfaceArrayOutputWithContext(ctx context.Context) GetVirtualMachineNetworkInterfaceArrayOutput {
	return o
}

func (o GetVirtualMachineNetworkInterfaceArrayOutput) Index(i pulumi.IntInput) GetVirtualMachineNetworkInterfaceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetVirtualMachineNetworkInterface {
		return vs[0].([]GetVirtualMachineNetworkInterface)[vs[1].(int)]
	}).(GetVirtualMachineNetworkInterfaceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineCloudinitInput)(nil)).Elem(), VirtualMachineCloudinitArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineCloudinitPtrInput)(nil)).Elem(), VirtualMachineCloudinitArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineDiskInput)(nil)).Elem(), VirtualMachineDiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineDiskArrayInput)(nil)).Elem(), VirtualMachineDiskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineNetworkInterfaceInput)(nil)).Elem(), VirtualMachineNetworkInterfaceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineNetworkInterfaceArrayInput)(nil)).Elem(), VirtualMachineNetworkInterfaceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVirtualMachineCloudinitInput)(nil)).Elem(), GetVirtualMachineCloudinitArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVirtualMachineCloudinitArrayInput)(nil)).Elem(), GetVirtualMachineCloudinitArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVirtualMachineDiskInput)(nil)).Elem(), GetVirtualMachineDiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVirtualMachineDiskArrayInput)(nil)).Elem(), GetVirtualMachineDiskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVirtualMachineNetworkInterfaceInput)(nil)).Elem(), GetVirtualMachineNetworkInterfaceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVirtualMachineNetworkInterfaceArrayInput)(nil)).Elem(), GetVirtualMachineNetworkInterfaceArray{})
	pulumi.RegisterOutputType(VirtualMachineCloudinitOutput{})
	pulumi.RegisterOutputType(VirtualMachineCloudinitPtrOutput{})
	pulumi.RegisterOutputType(VirtualMachineDiskOutput{})
	pulumi.RegisterOutputType(VirtualMachineDiskArrayOutput{})
	pulumi.RegisterOutputType(VirtualMachineNetworkInterfaceOutput{})
	pulumi.RegisterOutputType(VirtualMachineNetworkInterfaceArrayOutput{})
	pulumi.RegisterOutputType(GetVirtualMachineCloudinitOutput{})
	pulumi.RegisterOutputType(GetVirtualMachineCloudinitArrayOutput{})
	pulumi.RegisterOutputType(GetVirtualMachineDiskOutput{})
	pulumi.RegisterOutputType(GetVirtualMachineDiskArrayOutput{})
	pulumi.RegisterOutputType(GetVirtualMachineNetworkInterfaceOutput{})
	pulumi.RegisterOutputType(GetVirtualMachineNetworkInterfaceArrayOutput{})
}
