// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package harvester

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type VirtualMachineCloudinit struct {
	NetworkData           *string `pulumi:"networkData"`
	NetworkDataBase64     *string `pulumi:"networkDataBase64"`
	NetworkDataSecretName *string `pulumi:"networkDataSecretName"`
	Type                  *string `pulumi:"type"`
	UserData              *string `pulumi:"userData"`
	UserDataBase64        *string `pulumi:"userDataBase64"`
	UserDataSecretName    *string `pulumi:"userDataSecretName"`
}

// VirtualMachineCloudinitInput is an input type that accepts VirtualMachineCloudinitArgs and VirtualMachineCloudinitOutput values.
// You can construct a concrete instance of `VirtualMachineCloudinitInput` via:
//
//          VirtualMachineCloudinitArgs{...}
type VirtualMachineCloudinitInput interface {
	pulumi.Input

	ToVirtualMachineCloudinitOutput() VirtualMachineCloudinitOutput
	ToVirtualMachineCloudinitOutputWithContext(context.Context) VirtualMachineCloudinitOutput
}

type VirtualMachineCloudinitArgs struct {
	NetworkData           pulumi.StringPtrInput `pulumi:"networkData"`
	NetworkDataBase64     pulumi.StringPtrInput `pulumi:"networkDataBase64"`
	NetworkDataSecretName pulumi.StringPtrInput `pulumi:"networkDataSecretName"`
	Type                  pulumi.StringPtrInput `pulumi:"type"`
	UserData              pulumi.StringPtrInput `pulumi:"userData"`
	UserDataBase64        pulumi.StringPtrInput `pulumi:"userDataBase64"`
	UserDataSecretName    pulumi.StringPtrInput `pulumi:"userDataSecretName"`
}

func (VirtualMachineCloudinitArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineCloudinit)(nil)).Elem()
}

func (i VirtualMachineCloudinitArgs) ToVirtualMachineCloudinitOutput() VirtualMachineCloudinitOutput {
	return i.ToVirtualMachineCloudinitOutputWithContext(context.Background())
}

func (i VirtualMachineCloudinitArgs) ToVirtualMachineCloudinitOutputWithContext(ctx context.Context) VirtualMachineCloudinitOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineCloudinitOutput)
}

func (i VirtualMachineCloudinitArgs) ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput {
	return i.ToVirtualMachineCloudinitPtrOutputWithContext(context.Background())
}

func (i VirtualMachineCloudinitArgs) ToVirtualMachineCloudinitPtrOutputWithContext(ctx context.Context) VirtualMachineCloudinitPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineCloudinitOutput).ToVirtualMachineCloudinitPtrOutputWithContext(ctx)
}

// VirtualMachineCloudinitPtrInput is an input type that accepts VirtualMachineCloudinitArgs, VirtualMachineCloudinitPtr and VirtualMachineCloudinitPtrOutput values.
// You can construct a concrete instance of `VirtualMachineCloudinitPtrInput` via:
//
//          VirtualMachineCloudinitArgs{...}
//
//  or:
//
//          nil
type VirtualMachineCloudinitPtrInput interface {
	pulumi.Input

	ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput
	ToVirtualMachineCloudinitPtrOutputWithContext(context.Context) VirtualMachineCloudinitPtrOutput
}

type virtualMachineCloudinitPtrType VirtualMachineCloudinitArgs

func VirtualMachineCloudinitPtr(v *VirtualMachineCloudinitArgs) VirtualMachineCloudinitPtrInput {
	return (*virtualMachineCloudinitPtrType)(v)
}

func (*virtualMachineCloudinitPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualMachineCloudinit)(nil)).Elem()
}

func (i *virtualMachineCloudinitPtrType) ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput {
	return i.ToVirtualMachineCloudinitPtrOutputWithContext(context.Background())
}

func (i *virtualMachineCloudinitPtrType) ToVirtualMachineCloudinitPtrOutputWithContext(ctx context.Context) VirtualMachineCloudinitPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineCloudinitPtrOutput)
}

type VirtualMachineCloudinitOutput struct{ *pulumi.OutputState }

func (VirtualMachineCloudinitOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineCloudinit)(nil)).Elem()
}

func (o VirtualMachineCloudinitOutput) ToVirtualMachineCloudinitOutput() VirtualMachineCloudinitOutput {
	return o
}

func (o VirtualMachineCloudinitOutput) ToVirtualMachineCloudinitOutputWithContext(ctx context.Context) VirtualMachineCloudinitOutput {
	return o
}

func (o VirtualMachineCloudinitOutput) ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput {
	return o.ToVirtualMachineCloudinitPtrOutputWithContext(context.Background())
}

func (o VirtualMachineCloudinitOutput) ToVirtualMachineCloudinitPtrOutputWithContext(ctx context.Context) VirtualMachineCloudinitPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v VirtualMachineCloudinit) *VirtualMachineCloudinit {
		return &v
	}).(VirtualMachineCloudinitPtrOutput)
}

func (o VirtualMachineCloudinitOutput) NetworkData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.NetworkData }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) NetworkDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.NetworkDataBase64 }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) NetworkDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.NetworkDataSecretName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) UserData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.UserData }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) UserDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.UserDataBase64 }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitOutput) UserDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineCloudinit) *string { return v.UserDataSecretName }).(pulumi.StringPtrOutput)
}

type VirtualMachineCloudinitPtrOutput struct{ *pulumi.OutputState }

func (VirtualMachineCloudinitPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualMachineCloudinit)(nil)).Elem()
}

func (o VirtualMachineCloudinitPtrOutput) ToVirtualMachineCloudinitPtrOutput() VirtualMachineCloudinitPtrOutput {
	return o
}

func (o VirtualMachineCloudinitPtrOutput) ToVirtualMachineCloudinitPtrOutputWithContext(ctx context.Context) VirtualMachineCloudinitPtrOutput {
	return o
}

func (o VirtualMachineCloudinitPtrOutput) Elem() VirtualMachineCloudinitOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) VirtualMachineCloudinit {
		if v != nil {
			return *v
		}
		var ret VirtualMachineCloudinit
		return ret
	}).(VirtualMachineCloudinitOutput)
}

func (o VirtualMachineCloudinitPtrOutput) NetworkData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.NetworkData
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) NetworkDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.NetworkDataBase64
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) NetworkDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.NetworkDataSecretName
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.Type
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) UserData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.UserData
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) UserDataBase64() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.UserDataBase64
	}).(pulumi.StringPtrOutput)
}

func (o VirtualMachineCloudinitPtrOutput) UserDataSecretName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualMachineCloudinit) *string {
		if v == nil {
			return nil
		}
		return v.UserDataSecretName
	}).(pulumi.StringPtrOutput)
}

type VirtualMachineDisk struct {
	AccessMode         *string `pulumi:"accessMode"`
	AutoDelete         *bool   `pulumi:"autoDelete"`
	BootOrder          *int    `pulumi:"bootOrder"`
	Bus                *string `pulumi:"bus"`
	ContainerImageName *string `pulumi:"containerImageName"`
	ExistingVolumeName *string `pulumi:"existingVolumeName"`
	Image              *string `pulumi:"image"`
	Name               string  `pulumi:"name"`
	Size               *string `pulumi:"size"`
	StorageClassName   *string `pulumi:"storageClassName"`
	Type               *string `pulumi:"type"`
	VolumeMode         *string `pulumi:"volumeMode"`
	VolumeName         *string `pulumi:"volumeName"`
}

// VirtualMachineDiskInput is an input type that accepts VirtualMachineDiskArgs and VirtualMachineDiskOutput values.
// You can construct a concrete instance of `VirtualMachineDiskInput` via:
//
//          VirtualMachineDiskArgs{...}
type VirtualMachineDiskInput interface {
	pulumi.Input

	ToVirtualMachineDiskOutput() VirtualMachineDiskOutput
	ToVirtualMachineDiskOutputWithContext(context.Context) VirtualMachineDiskOutput
}

type VirtualMachineDiskArgs struct {
	AccessMode         pulumi.StringPtrInput `pulumi:"accessMode"`
	AutoDelete         pulumi.BoolPtrInput   `pulumi:"autoDelete"`
	BootOrder          pulumi.IntPtrInput    `pulumi:"bootOrder"`
	Bus                pulumi.StringPtrInput `pulumi:"bus"`
	ContainerImageName pulumi.StringPtrInput `pulumi:"containerImageName"`
	ExistingVolumeName pulumi.StringPtrInput `pulumi:"existingVolumeName"`
	Image              pulumi.StringPtrInput `pulumi:"image"`
	Name               pulumi.StringInput    `pulumi:"name"`
	Size               pulumi.StringPtrInput `pulumi:"size"`
	StorageClassName   pulumi.StringPtrInput `pulumi:"storageClassName"`
	Type               pulumi.StringPtrInput `pulumi:"type"`
	VolumeMode         pulumi.StringPtrInput `pulumi:"volumeMode"`
	VolumeName         pulumi.StringPtrInput `pulumi:"volumeName"`
}

func (VirtualMachineDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineDisk)(nil)).Elem()
}

func (i VirtualMachineDiskArgs) ToVirtualMachineDiskOutput() VirtualMachineDiskOutput {
	return i.ToVirtualMachineDiskOutputWithContext(context.Background())
}

func (i VirtualMachineDiskArgs) ToVirtualMachineDiskOutputWithContext(ctx context.Context) VirtualMachineDiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineDiskOutput)
}

// VirtualMachineDiskArrayInput is an input type that accepts VirtualMachineDiskArray and VirtualMachineDiskArrayOutput values.
// You can construct a concrete instance of `VirtualMachineDiskArrayInput` via:
//
//          VirtualMachineDiskArray{ VirtualMachineDiskArgs{...} }
type VirtualMachineDiskArrayInput interface {
	pulumi.Input

	ToVirtualMachineDiskArrayOutput() VirtualMachineDiskArrayOutput
	ToVirtualMachineDiskArrayOutputWithContext(context.Context) VirtualMachineDiskArrayOutput
}

type VirtualMachineDiskArray []VirtualMachineDiskInput

func (VirtualMachineDiskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualMachineDisk)(nil)).Elem()
}

func (i VirtualMachineDiskArray) ToVirtualMachineDiskArrayOutput() VirtualMachineDiskArrayOutput {
	return i.ToVirtualMachineDiskArrayOutputWithContext(context.Background())
}

func (i VirtualMachineDiskArray) ToVirtualMachineDiskArrayOutputWithContext(ctx context.Context) VirtualMachineDiskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineDiskArrayOutput)
}

type VirtualMachineDiskOutput struct{ *pulumi.OutputState }

func (VirtualMachineDiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineDisk)(nil)).Elem()
}

func (o VirtualMachineDiskOutput) ToVirtualMachineDiskOutput() VirtualMachineDiskOutput {
	return o
}

func (o VirtualMachineDiskOutput) ToVirtualMachineDiskOutputWithContext(ctx context.Context) VirtualMachineDiskOutput {
	return o
}

func (o VirtualMachineDiskOutput) AccessMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.AccessMode }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) AutoDelete() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *bool { return v.AutoDelete }).(pulumi.BoolPtrOutput)
}

func (o VirtualMachineDiskOutput) BootOrder() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *int { return v.BootOrder }).(pulumi.IntPtrOutput)
}

func (o VirtualMachineDiskOutput) Bus() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.Bus }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) ContainerImageName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.ContainerImageName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) ExistingVolumeName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.ExistingVolumeName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.Image }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v VirtualMachineDisk) string { return v.Name }).(pulumi.StringOutput)
}

func (o VirtualMachineDiskOutput) Size() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.Size }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) StorageClassName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.StorageClassName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) VolumeMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.VolumeMode }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineDiskOutput) VolumeName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineDisk) *string { return v.VolumeName }).(pulumi.StringPtrOutput)
}

type VirtualMachineDiskArrayOutput struct{ *pulumi.OutputState }

func (VirtualMachineDiskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualMachineDisk)(nil)).Elem()
}

func (o VirtualMachineDiskArrayOutput) ToVirtualMachineDiskArrayOutput() VirtualMachineDiskArrayOutput {
	return o
}

func (o VirtualMachineDiskArrayOutput) ToVirtualMachineDiskArrayOutputWithContext(ctx context.Context) VirtualMachineDiskArrayOutput {
	return o
}

func (o VirtualMachineDiskArrayOutput) Index(i pulumi.IntInput) VirtualMachineDiskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) VirtualMachineDisk {
		return vs[0].([]VirtualMachineDisk)[vs[1].(int)]
	}).(VirtualMachineDiskOutput)
}

type VirtualMachineNetworkInterface struct {
	InterfaceName *string `pulumi:"interfaceName"`
	IpAddress     *string `pulumi:"ipAddress"`
	MacAddress    *string `pulumi:"macAddress"`
	Model         *string `pulumi:"model"`
	Name          string  `pulumi:"name"`
	NetworkName   *string `pulumi:"networkName"`
	Type          *string `pulumi:"type"`
}

// VirtualMachineNetworkInterfaceInput is an input type that accepts VirtualMachineNetworkInterfaceArgs and VirtualMachineNetworkInterfaceOutput values.
// You can construct a concrete instance of `VirtualMachineNetworkInterfaceInput` via:
//
//          VirtualMachineNetworkInterfaceArgs{...}
type VirtualMachineNetworkInterfaceInput interface {
	pulumi.Input

	ToVirtualMachineNetworkInterfaceOutput() VirtualMachineNetworkInterfaceOutput
	ToVirtualMachineNetworkInterfaceOutputWithContext(context.Context) VirtualMachineNetworkInterfaceOutput
}

type VirtualMachineNetworkInterfaceArgs struct {
	InterfaceName pulumi.StringPtrInput `pulumi:"interfaceName"`
	IpAddress     pulumi.StringPtrInput `pulumi:"ipAddress"`
	MacAddress    pulumi.StringPtrInput `pulumi:"macAddress"`
	Model         pulumi.StringPtrInput `pulumi:"model"`
	Name          pulumi.StringInput    `pulumi:"name"`
	NetworkName   pulumi.StringPtrInput `pulumi:"networkName"`
	Type          pulumi.StringPtrInput `pulumi:"type"`
}

func (VirtualMachineNetworkInterfaceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineNetworkInterface)(nil)).Elem()
}

func (i VirtualMachineNetworkInterfaceArgs) ToVirtualMachineNetworkInterfaceOutput() VirtualMachineNetworkInterfaceOutput {
	return i.ToVirtualMachineNetworkInterfaceOutputWithContext(context.Background())
}

func (i VirtualMachineNetworkInterfaceArgs) ToVirtualMachineNetworkInterfaceOutputWithContext(ctx context.Context) VirtualMachineNetworkInterfaceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineNetworkInterfaceOutput)
}

// VirtualMachineNetworkInterfaceArrayInput is an input type that accepts VirtualMachineNetworkInterfaceArray and VirtualMachineNetworkInterfaceArrayOutput values.
// You can construct a concrete instance of `VirtualMachineNetworkInterfaceArrayInput` via:
//
//          VirtualMachineNetworkInterfaceArray{ VirtualMachineNetworkInterfaceArgs{...} }
type VirtualMachineNetworkInterfaceArrayInput interface {
	pulumi.Input

	ToVirtualMachineNetworkInterfaceArrayOutput() VirtualMachineNetworkInterfaceArrayOutput
	ToVirtualMachineNetworkInterfaceArrayOutputWithContext(context.Context) VirtualMachineNetworkInterfaceArrayOutput
}

type VirtualMachineNetworkInterfaceArray []VirtualMachineNetworkInterfaceInput

func (VirtualMachineNetworkInterfaceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualMachineNetworkInterface)(nil)).Elem()
}

func (i VirtualMachineNetworkInterfaceArray) ToVirtualMachineNetworkInterfaceArrayOutput() VirtualMachineNetworkInterfaceArrayOutput {
	return i.ToVirtualMachineNetworkInterfaceArrayOutputWithContext(context.Background())
}

func (i VirtualMachineNetworkInterfaceArray) ToVirtualMachineNetworkInterfaceArrayOutputWithContext(ctx context.Context) VirtualMachineNetworkInterfaceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineNetworkInterfaceArrayOutput)
}

type VirtualMachineNetworkInterfaceOutput struct{ *pulumi.OutputState }

func (VirtualMachineNetworkInterfaceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineNetworkInterface)(nil)).Elem()
}

func (o VirtualMachineNetworkInterfaceOutput) ToVirtualMachineNetworkInterfaceOutput() VirtualMachineNetworkInterfaceOutput {
	return o
}

func (o VirtualMachineNetworkInterfaceOutput) ToVirtualMachineNetworkInterfaceOutputWithContext(ctx context.Context) VirtualMachineNetworkInterfaceOutput {
	return o
}

func (o VirtualMachineNetworkInterfaceOutput) InterfaceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.InterfaceName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) IpAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.IpAddress }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) MacAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.MacAddress }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) Model() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.Model }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) string { return v.Name }).(pulumi.StringOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) NetworkName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.NetworkName }).(pulumi.StringPtrOutput)
}

func (o VirtualMachineNetworkInterfaceOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualMachineNetworkInterface) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type VirtualMachineNetworkInterfaceArrayOutput struct{ *pulumi.OutputState }

func (VirtualMachineNetworkInterfaceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualMachineNetworkInterface)(nil)).Elem()
}

func (o VirtualMachineNetworkInterfaceArrayOutput) ToVirtualMachineNetworkInterfaceArrayOutput() VirtualMachineNetworkInterfaceArrayOutput {
	return o
}

func (o VirtualMachineNetworkInterfaceArrayOutput) ToVirtualMachineNetworkInterfaceArrayOutputWithContext(ctx context.Context) VirtualMachineNetworkInterfaceArrayOutput {
	return o
}

func (o VirtualMachineNetworkInterfaceArrayOutput) Index(i pulumi.IntInput) VirtualMachineNetworkInterfaceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) VirtualMachineNetworkInterface {
		return vs[0].([]VirtualMachineNetworkInterface)[vs[1].(int)]
	}).(VirtualMachineNetworkInterfaceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineCloudinitInput)(nil)).Elem(), VirtualMachineCloudinitArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineCloudinitPtrInput)(nil)).Elem(), VirtualMachineCloudinitArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineDiskInput)(nil)).Elem(), VirtualMachineDiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineDiskArrayInput)(nil)).Elem(), VirtualMachineDiskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineNetworkInterfaceInput)(nil)).Elem(), VirtualMachineNetworkInterfaceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineNetworkInterfaceArrayInput)(nil)).Elem(), VirtualMachineNetworkInterfaceArray{})
	pulumi.RegisterOutputType(VirtualMachineCloudinitOutput{})
	pulumi.RegisterOutputType(VirtualMachineCloudinitPtrOutput{})
	pulumi.RegisterOutputType(VirtualMachineDiskOutput{})
	pulumi.RegisterOutputType(VirtualMachineDiskArrayOutput{})
	pulumi.RegisterOutputType(VirtualMachineNetworkInterfaceOutput{})
	pulumi.RegisterOutputType(VirtualMachineNetworkInterfaceArrayOutput{})
}
