// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package harvester

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/huaxk/pulumi-harvester/sdk/go/harvester"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := harvester.NewVolume(ctx, "ubuntu20-dev-mount-disk", &harvester.VolumeArgs{
// 			Namespace: pulumi.String("default"),
// 			Size:      pulumi.String("10Gi"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		_, err = harvester.NewVolume(ctx, "ubuntu20-dev-image-disk", &harvester.VolumeArgs{
// 			Image:     pulumi.String("harvester-public/ubuntu20"),
// 			Namespace: pulumi.String("default"),
// 			Size:      pulumi.String("10Gi"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// ```sh
//  $ pulumi import harvester:index/volume:Volume foo <Namespace>/<Name>
// ```
type Volume struct {
	pulumi.CustomResourceState

	AccessMode pulumi.StringPtrOutput `pulumi:"accessMode"`
	AttachedVm pulumi.StringOutput    `pulumi:"attachedVm"`
	// Any text you want that better describes this resource
	Description pulumi.StringPtrOutput `pulumi:"description"`
	Image       pulumi.StringPtrOutput `pulumi:"image"`
	// A unique name
	Name             pulumi.StringOutput    `pulumi:"name"`
	Namespace        pulumi.StringPtrOutput `pulumi:"namespace"`
	Phase            pulumi.StringOutput    `pulumi:"phase"`
	Size             pulumi.StringPtrOutput `pulumi:"size"`
	State            pulumi.StringOutput    `pulumi:"state"`
	StorageClassName pulumi.StringOutput    `pulumi:"storageClassName"`
	Tags             pulumi.MapOutput       `pulumi:"tags"`
	VolumeMode       pulumi.StringPtrOutput `pulumi:"volumeMode"`
}

// NewVolume registers a new resource with the given unique name, arguments, and options.
func NewVolume(ctx *pulumi.Context,
	name string, args *VolumeArgs, opts ...pulumi.ResourceOption) (*Volume, error) {
	if args == nil {
		args = &VolumeArgs{}
	}

	var resource Volume
	err := ctx.RegisterResource("harvester:index/volume:Volume", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVolume gets an existing Volume resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVolume(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VolumeState, opts ...pulumi.ResourceOption) (*Volume, error) {
	var resource Volume
	err := ctx.ReadResource("harvester:index/volume:Volume", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Volume resources.
type volumeState struct {
	AccessMode *string `pulumi:"accessMode"`
	AttachedVm *string `pulumi:"attachedVm"`
	// Any text you want that better describes this resource
	Description *string `pulumi:"description"`
	Image       *string `pulumi:"image"`
	// A unique name
	Name             *string                `pulumi:"name"`
	Namespace        *string                `pulumi:"namespace"`
	Phase            *string                `pulumi:"phase"`
	Size             *string                `pulumi:"size"`
	State            *string                `pulumi:"state"`
	StorageClassName *string                `pulumi:"storageClassName"`
	Tags             map[string]interface{} `pulumi:"tags"`
	VolumeMode       *string                `pulumi:"volumeMode"`
}

type VolumeState struct {
	AccessMode pulumi.StringPtrInput
	AttachedVm pulumi.StringPtrInput
	// Any text you want that better describes this resource
	Description pulumi.StringPtrInput
	Image       pulumi.StringPtrInput
	// A unique name
	Name             pulumi.StringPtrInput
	Namespace        pulumi.StringPtrInput
	Phase            pulumi.StringPtrInput
	Size             pulumi.StringPtrInput
	State            pulumi.StringPtrInput
	StorageClassName pulumi.StringPtrInput
	Tags             pulumi.MapInput
	VolumeMode       pulumi.StringPtrInput
}

func (VolumeState) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeState)(nil)).Elem()
}

type volumeArgs struct {
	AccessMode *string `pulumi:"accessMode"`
	// Any text you want that better describes this resource
	Description *string `pulumi:"description"`
	Image       *string `pulumi:"image"`
	// A unique name
	Name             *string                `pulumi:"name"`
	Namespace        *string                `pulumi:"namespace"`
	Size             *string                `pulumi:"size"`
	StorageClassName *string                `pulumi:"storageClassName"`
	Tags             map[string]interface{} `pulumi:"tags"`
	VolumeMode       *string                `pulumi:"volumeMode"`
}

// The set of arguments for constructing a Volume resource.
type VolumeArgs struct {
	AccessMode pulumi.StringPtrInput
	// Any text you want that better describes this resource
	Description pulumi.StringPtrInput
	Image       pulumi.StringPtrInput
	// A unique name
	Name             pulumi.StringPtrInput
	Namespace        pulumi.StringPtrInput
	Size             pulumi.StringPtrInput
	StorageClassName pulumi.StringPtrInput
	Tags             pulumi.MapInput
	VolumeMode       pulumi.StringPtrInput
}

func (VolumeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeArgs)(nil)).Elem()
}

type VolumeInput interface {
	pulumi.Input

	ToVolumeOutput() VolumeOutput
	ToVolumeOutputWithContext(ctx context.Context) VolumeOutput
}

func (*Volume) ElementType() reflect.Type {
	return reflect.TypeOf((**Volume)(nil)).Elem()
}

func (i *Volume) ToVolumeOutput() VolumeOutput {
	return i.ToVolumeOutputWithContext(context.Background())
}

func (i *Volume) ToVolumeOutputWithContext(ctx context.Context) VolumeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeOutput)
}

// VolumeArrayInput is an input type that accepts VolumeArray and VolumeArrayOutput values.
// You can construct a concrete instance of `VolumeArrayInput` via:
//
//          VolumeArray{ VolumeArgs{...} }
type VolumeArrayInput interface {
	pulumi.Input

	ToVolumeArrayOutput() VolumeArrayOutput
	ToVolumeArrayOutputWithContext(context.Context) VolumeArrayOutput
}

type VolumeArray []VolumeInput

func (VolumeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Volume)(nil)).Elem()
}

func (i VolumeArray) ToVolumeArrayOutput() VolumeArrayOutput {
	return i.ToVolumeArrayOutputWithContext(context.Background())
}

func (i VolumeArray) ToVolumeArrayOutputWithContext(ctx context.Context) VolumeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeArrayOutput)
}

// VolumeMapInput is an input type that accepts VolumeMap and VolumeMapOutput values.
// You can construct a concrete instance of `VolumeMapInput` via:
//
//          VolumeMap{ "key": VolumeArgs{...} }
type VolumeMapInput interface {
	pulumi.Input

	ToVolumeMapOutput() VolumeMapOutput
	ToVolumeMapOutputWithContext(context.Context) VolumeMapOutput
}

type VolumeMap map[string]VolumeInput

func (VolumeMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Volume)(nil)).Elem()
}

func (i VolumeMap) ToVolumeMapOutput() VolumeMapOutput {
	return i.ToVolumeMapOutputWithContext(context.Background())
}

func (i VolumeMap) ToVolumeMapOutputWithContext(ctx context.Context) VolumeMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeMapOutput)
}

type VolumeOutput struct{ *pulumi.OutputState }

func (VolumeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Volume)(nil)).Elem()
}

func (o VolumeOutput) ToVolumeOutput() VolumeOutput {
	return o
}

func (o VolumeOutput) ToVolumeOutputWithContext(ctx context.Context) VolumeOutput {
	return o
}

type VolumeArrayOutput struct{ *pulumi.OutputState }

func (VolumeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Volume)(nil)).Elem()
}

func (o VolumeArrayOutput) ToVolumeArrayOutput() VolumeArrayOutput {
	return o
}

func (o VolumeArrayOutput) ToVolumeArrayOutputWithContext(ctx context.Context) VolumeArrayOutput {
	return o
}

func (o VolumeArrayOutput) Index(i pulumi.IntInput) VolumeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Volume {
		return vs[0].([]*Volume)[vs[1].(int)]
	}).(VolumeOutput)
}

type VolumeMapOutput struct{ *pulumi.OutputState }

func (VolumeMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Volume)(nil)).Elem()
}

func (o VolumeMapOutput) ToVolumeMapOutput() VolumeMapOutput {
	return o
}

func (o VolumeMapOutput) ToVolumeMapOutputWithContext(ctx context.Context) VolumeMapOutput {
	return o
}

func (o VolumeMapOutput) MapIndex(k pulumi.StringInput) VolumeOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Volume {
		return vs[0].(map[string]*Volume)[vs[1].(string)]
	}).(VolumeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeInput)(nil)).Elem(), &Volume{})
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeArrayInput)(nil)).Elem(), VolumeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeMapInput)(nil)).Elem(), VolumeMap{})
	pulumi.RegisterOutputType(VolumeOutput{})
	pulumi.RegisterOutputType(VolumeArrayOutput{})
	pulumi.RegisterOutputType(VolumeMapOutput{})
}
