// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface GetVirtualMachineCloudinit {
    networkData?: string;
    networkDataBase64?: string;
    networkDataSecretName?: string;
    type?: string;
    userData?: string;
    userDataBase64?: string;
    userDataSecretName?: string;
}

export interface GetVirtualMachineDisk {
    accessMode: string;
    autoDelete: boolean;
    bootOrder?: number;
    bus: string;
    containerImageName?: string;
    existingVolumeName?: string;
    hotPlug: boolean;
    image?: string;
    /**
     * A unique name
     */
    name: string;
    size?: string;
    storageClassName: string;
    type?: string;
    volumeMode: string;
    volumeName: string;
}

export interface GetVirtualMachineNetworkInterface {
    interfaceName: string;
    ipAddress: string;
    macAddress: string;
    model?: string;
    /**
     * A unique name
     */
    name: string;
    networkName?: string;
    type: string;
}

export interface VirtualMachineCloudinit {
    networkData?: string;
    networkDataBase64?: string;
    networkDataSecretName?: string;
    type?: string;
    userData?: string;
    userDataBase64?: string;
    userDataSecretName?: string;
}

export interface VirtualMachineDisk {
    accessMode: string;
    autoDelete: boolean;
    bootOrder?: number;
    bus: string;
    containerImageName?: string;
    existingVolumeName?: string;
    hotPlug: boolean;
    image?: string;
    /**
     * A unique name
     */
    name: string;
    size?: string;
    storageClassName: string;
    type?: string;
    volumeMode: string;
    volumeName: string;
}

export interface VirtualMachineNetworkInterface {
    interfaceName: string;
    ipAddress: string;
    macAddress: string;
    model?: string;
    /**
     * A unique name
     */
    name: string;
    networkName?: string;
    type: string;
}

