// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Harvester.Inputs
{

    public sealed class VirtualMachineCloudinitArgs : Pulumi.ResourceArgs
    {
        [Input("networkData")]
        public Input<string>? NetworkData { get; set; }

        [Input("networkDataBase64")]
        public Input<string>? NetworkDataBase64 { get; set; }

        [Input("networkDataSecretName")]
        public Input<string>? NetworkDataSecretName { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("userData")]
        public Input<string>? UserData { get; set; }

        [Input("userDataBase64")]
        public Input<string>? UserDataBase64 { get; set; }

        [Input("userDataSecretName")]
        public Input<string>? UserDataSecretName { get; set; }

        public VirtualMachineCloudinitArgs()
        {
        }
    }
}
