// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as harvester from "@pulumi/harvester";
 *
 * const ubuntu20_dev_mount_disk = pulumi.output(harvester.getVolume({
 *     name: "ubuntu20-dev-mount-disk",
 *     namespace: "default",
 * }));
 * ```
 */
export function getVolume(args: GetVolumeArgs, opts?: pulumi.InvokeOptions): Promise<GetVolumeResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("harvester:index/getVolume:getVolume", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getVolume.
 */
export interface GetVolumeArgs {
    /**
     * A unique name
     */
    name: string;
    namespace?: string;
}

/**
 * A collection of values returned by getVolume.
 */
export interface GetVolumeResult {
    readonly accessMode: string;
    readonly attachedVm: string;
    /**
     * Any text you want that better describes this resource
     */
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly image: string;
    /**
     * A unique name
     */
    readonly name: string;
    readonly namespace?: string;
    readonly phase: string;
    readonly size: string;
    readonly state: string;
    readonly storageClassName: string;
    readonly tags: {[key: string]: any};
    readonly volumeMode: string;
}

export function getVolumeOutput(args: GetVolumeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVolumeResult> {
    return pulumi.output(args).apply(a => getVolume(a, opts))
}

/**
 * A collection of arguments for invoking getVolume.
 */
export interface GetVolumeOutputArgs {
    /**
     * A unique name
     */
    name: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
}
